# Generated by Django 5.0.1 on 2024-02-05 23:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsItem",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("job", "Job"),
                            ("story", "Story"),
                            ("comment", "Comment"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "news_source",
                    models.CharField(
                        choices=[("HN", "Hacker News"), ("HF", "Hackers Feed")],
                        default="HF",
                        max_length=100,
                    ),
                ),
                ("by", models.CharField(max_length=100)),
                ("time", models.DateTimeField(default=django.utils.timezone.now)),
                ("text", models.TextField(blank=True, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                ("score", models.IntegerField(default=0, null=True)),
                ("title", models.CharField(max_length=255)),
                ("descendants", models.IntegerField(default=0, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment_id", models.IntegerField(blank=True, null=True)),
                ("by", models.CharField(default="Anonymous", max_length=100)),
                ("time", models.DateTimeField(default=django.utils.timezone.now)),
                ("text", models.TextField(null=True)),
                (
                    "parent_comment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "news_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="news.newsitem"
                    ),
                ),
            ],
        ),
    ]
